name: Package (Mac)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clean:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: xcodebuild clean -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CrystalButtonKit
          DESTINATION: platform=macOS

  build:
    needs: clean

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Clean Build
      run: xcodebuild build -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CrystalButtonKit
          DESTINATION: platform=macOS
