name: Test

on:
  workflow_run:
    workflows: [Package]
    types:
      - completed
  pull_request:
    branches: [ "main" ]

jobs:
  clean:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Clean
      run: xcodebuild clean -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CrystalButtonKit
          DESTINATION: platform=iOS Simulator,name=iPhone 13 Pro


  build:
    needs: clean

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Clean Build
      run: xcodebuild build -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CrystalButtonKit
          DESTINATION: platform=iOS Simulator,name=iPhone 13 Pro
          
  test:
    needs: build
    
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Test
      run: xcodebuild test -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CrystalButtonKit
          DESTINATION: platform=iOS Simulator,name=iPhone 13 Pro
